import io
import zipfile
from fpdf import FPDF
from typing import Dict, Any

class ExportService:
    """
    Handles generation of downloadable files (PDF, ZIP, SRT).
    """

    @staticmethod
    def generate_pdf_report(project_data: dict) -> bytes:
        """Generates a clean PDF report of the project."""
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("helvetica", "B", 16)
        
        topic = project_data.get("input", {}).get("topic", "SparkStudio Project")
        pdf.cell(0, 10, f"SparkStudio Report: {topic}", ln=True, align="C")
        pdf.ln(10)
        
        pdf.set_font("helvetica", size=12)
        
        # Just writing a simple summary for now
        pdf.multi_cell(0, 10, "This is an automated content production report generated by SparkStudio AI.")
        pdf.ln(5)
        
        if "script" in project_data:
            pdf.set_font("helvetica", "B", 14)
            pdf.cell(0, 10, "Video Script", ln=True)
            pdf.set_font("helvetica", size=11)
            # FPDF sometimes struggles with utf-8 special chars, so encode/decode
            script_text = str(project_data["script"].get("full_script", "")).encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 10, script_text)
            
        return pdf.output()

    @staticmethod
    def generate_zip_package(project_data: dict) -> bytes:
        """Packages all outputs into a ZIP file."""
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            # Add Script
            if "script" in project_data:
                zip_file.writestr("script.txt", project_data["script"].get("full_script", ""))
                
            # Add Subtitles
            if "subtitles" in project_data:
                zip_file.writestr("captions.srt", project_data["subtitles"].get("srt_content", ""))
                zip_file.writestr("captions.vtt", project_data["subtitles"].get("vtt_content", ""))
                
            # Add PDF Report
            pdf_bytes = ExportService.generate_pdf_report(project_data)
            zip_file.writestr("report.pdf", pdf_bytes)
            
        zip_buffer.seek(0)
        return zip_buffer.getvalue()
