import io
import zipfile
import time
from fpdf import FPDF
from typing import Dict, Any

def clean_str(s: Any) -> str:
    """Helper to convert unicode strings to compatible latin-1 characters to prevent FPDF encode errors."""
    if not s:
        return ""
    s_str = str(s)
    # Common replacements
    replacements = {
        "\u201c": '"', "\u201d": '"',
        "\u2018": "'", "\u2019": "'",
        "\u2014": "-", "\u2013": "-",
        "\u2022": "*", "\u2026": "...",
        "\u2714": "[X]", "\u274c": "[ ]"
    }
    for k, v in replacements.items():
        s_str = s_str.replace(k, v)
    # Strip non-latin1 characters
    return s_str.encode("latin-1", "ignore").decode("latin-1")

class SparkStudioPDF(FPDF):
    """Custom FPDF layout with a premium dark-accent theme and structured headers/footers."""
    
    def header(self):
        if self.page_no() == 1:
            return  # No header on cover page
            
        # Top brand accent bar (Deep Purple)
        self.set_fill_color(108, 92, 231)
        self.rect(0, 0, 210, 4, "F")
        
        # Header text
        self.set_font("helvetica", "B", 8)
        self.set_text_color(140, 140, 150)
        self.cell(0, 12, "SPARKSTUDIO AI — CONTENT AUDIT & PRODUCTION REPORT", ln=False, align="L")
        self.set_font("helvetica", "", 8)
        self.cell(0, 12, "CONFIDENTIAL", ln=True, align="R")
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(150, 150, 160)
        
        # Subtle horizontal divider line
        self.set_draw_color(220, 220, 225)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        
        # Footer text and pagination
        self.cell(0, 10, f"Page {self.page_no()} | Generated by SparkStudio AI", align="C")

class ExportService:
    """
    Handles generation of downloadable files (PDF, ZIP, SRT).
    """

    @staticmethod
    def generate_pdf_report(project_data: dict) -> bytes:
        """Generates a premium, highly formatted PDF report of the project."""
        # Initialize custom styled PDF
        pdf = SparkStudioPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        
        # Extract inputs
        input_data = project_data.get("input", {})
        topic = clean_str(input_data.get("topic", "Untitled Project"))
        platform = clean_str(input_data.get("platform", "YouTube Shorts"))
        audience = clean_str(input_data.get("audience", "General Audience"))
        tone = clean_str(input_data.get("tone", "Professional"))
        video_length = clean_str(str(input_data.get("video_length", "60s")))
        
        # ──────────────────────────────────────────────────────────────────
        # PAGE 1: Premium Cover Page
        # ──────────────────────────────────────────────────────────────────
        pdf.add_page()
        
        # Decorative sidebar stripe (Deep Purple)
        pdf.set_fill_color(108, 92, 231)
        pdf.rect(0, 0, 15, 297, "F")
        
        # Shift margins past the sidebar stripe
        pdf.set_left_margin(25)
        pdf.set_y(40)
        
        # Brand Header
        pdf.set_font("helvetica", "B", 24)
        pdf.set_text_color(108, 92, 231)
        pdf.cell(0, 10, "SPARKSTUDIO AI", ln=True)
        
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(150, 150, 160)
        pdf.cell(0, 6, "INTELLIGENT CONTENT PRODUCTION SYSTEM", ln=True)
        pdf.ln(25)
        
        # Project Title
        pdf.set_font("helvetica", "B", 18)
        pdf.set_text_color(40, 40, 50)
        pdf.multi_cell(0, 8, f"Project Audit: {topic}")
        pdf.ln(5)
        
        # Horizontal rule
        pdf.set_draw_color(220, 220, 225)
        pdf.line(25, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(15)
        
        # Metadata / Brief Card
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(80, 80, 90)
        pdf.cell(0, 8, "Project Metadata Brief", ln=True)
        pdf.ln(2)
        
        # Draw background block for metadata
        pdf.set_fill_color(248, 248, 252)
        pdf.set_draw_color(225, 225, 235)
        current_y = pdf.get_y()
        pdf.rect(25, current_y, 170, 45, "FD")
        
        # Inner text for Metadata
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(120, 120, 130)
        pdf.set_y(current_y + 4)
        
        # Left column
        pdf.cell(85, 6, "  TARGET PLATFORM:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(40, 40, 50)
        pdf.cell(85, 6, platform, ln=True)
        
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(120, 120, 130)
        pdf.cell(85, 6, "  AUDIENCE SEGMENT:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(40, 40, 50)
        pdf.cell(85, 6, audience, ln=True)
        
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(120, 120, 130)
        pdf.cell(85, 6, "  VIDEO TONE:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(40, 40, 50)
        pdf.cell(85, 6, tone, ln=True)
        
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(120, 120, 130)
        pdf.cell(85, 6, "  TARGET LENGTH:", ln=False)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(40, 40, 50)
        pdf.cell(85, 6, f"{video_length} seconds", ln=True)
        
        pdf.set_y(current_y + 45 + 25)
        
        # Footer block on cover page
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(160, 160, 170)
        pdf.cell(0, 5, "This document contains production directives, script structures, visual prompts,", ln=True)
        pdf.cell(0, 5, "and SEO optimization tags compiled by SparkStudio AI's multi-agent system.", ln=True)
        
        # Reset margins for remaining pages
        pdf.set_left_margin(15)
        pdf.set_right_margin(15)
        
        # ──────────────────────────────────────────────────────────────────
        # PAGE 2: Research Strategy & Script
        # ──────────────────────────────────────────────────────────────────
        pdf.add_page()
        pdf.set_y(20)
        
        # Section 1 Header
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(108, 92, 231)
        pdf.cell(0, 10, "1. Research Strategy & Key Angles", ln=True)
        pdf.ln(2)
        
        if "research" in project_data and isinstance(project_data["research"], dict):
            research = project_data["research"]
            
            # Bullet point insights
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(70, 70, 80)
            pdf.cell(0, 6, "Hook Directions:", ln=True)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(50, 50, 60)
            hooks = research.get("hooks", [])
            for hook in hooks[:3]:
                pdf.multi_cell(0, 5, f"- {clean_str(hook)}")
            pdf.ln(4)
            
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(70, 70, 80)
            pdf.cell(0, 6, "Viral Audience Angles:", ln=True)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(50, 50, 60)
            angles = research.get("viral_angles", [])
            for angle in angles[:3]:
                pdf.multi_cell(0, 5, f"- {clean_str(angle)}")
            pdf.ln(4)
        else:
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(0, 6, "No strategy data available.", ln=True)
            pdf.ln(4)
            
        # Section 2 Header: Script
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(108, 92, 231)
        pdf.cell(0, 10, "2. Video Script & Narration Directives", ln=True)
        pdf.ln(2)
        
        if "script" in project_data and isinstance(project_data["script"], dict):
            script = project_data["script"]
            full_script = script.get("full_script", "")
            
            # Script block in a colored box
            pdf.set_fill_color(250, 250, 252)
            pdf.set_draw_color(225, 225, 230)
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(50, 50, 60)
            
            cleaned_script = clean_str(full_script)
            # Add padding by drawing rect and printing multiline text
            pdf.multi_cell(180, 6, cleaned_script, border=1, fill=True)
        else:
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(0, 6, "No script content available.", ln=True)
            
        # ──────────────────────────────────────────────────────────────────
        # PAGE 3: Storyboard
        # ──────────────────────────────────────────────────────────────────
        if "storyboard" in project_data and isinstance(project_data["storyboard"], dict):
            pdf.add_page()
            pdf.set_y(20)
            
            pdf.set_font("helvetica", "B", 14)
            pdf.set_text_color(108, 92, 231)
            pdf.cell(0, 10, "3. Storyboard & Scene Prompting", ln=True)
            pdf.ln(3)
            
            storyboard = project_data["storyboard"]
            scenes = storyboard.get("scenes", [])
            
            for scene in scenes:
                # Border box check to keep card on page
                scene_num = scene.get("scene_number", 1)
                duration = scene.get("duration", 0)
                angle = clean_str(scene.get("camera_angle", "Neutral"))
                prompt_txt = clean_str(scene.get("image_prompt", scene.get("visual_description", "")))
                broll = clean_str(scene.get("broll_suggestions", "N/A"))
                
                # Card Header
                pdf.set_fill_color(240, 238, 250)
                pdf.set_draw_color(108, 92, 231)
                pdf.set_font("helvetica", "B", 10)
                pdf.set_text_color(108, 92, 231)
                pdf.cell(180, 8, f" Scene {scene_num} ({duration}s) — Camera Angle: {angle}", border=1, ln=True, fill=True)
                
                # Card Content
                pdf.set_fill_color(252, 252, 254)
                pdf.set_font("helvetica", "", 9)
                pdf.set_text_color(60, 60, 70)
                
                # Scene details
                content_txt = f"AI Generation Prompt:\n{prompt_txt}\n\nB-Roll Action:\n{broll}"
                pdf.multi_cell(180, 5, content_txt, border="LRB", fill=True)
                pdf.ln(5)
                
        # ──────────────────────────────────────────────────────────────────
        # PAGE 4: SEO & Quality Audit
        # ──────────────────────────────────────────────────────────────────
        pdf.add_page()
        pdf.set_y(20)
        
        # Section 4 Header: SEO Metadata
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(108, 92, 231)
        pdf.cell(0, 10, "4. Search Engine Optimisation (SEO)", ln=True)
        pdf.ln(2)
        
        if "seo" in project_data and isinstance(project_data["seo"], dict):
            seo = project_data["seo"]
            
            pdf.set_fill_color(248, 248, 250)
            pdf.set_draw_color(220, 220, 230)
            current_y = pdf.get_y()
            pdf.rect(15, current_y, 180, 45, "FD")
            pdf.set_y(current_y + 3)
            
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(108, 92, 231)
            pdf.cell(40, 6, "  Recommended Title:", ln=False)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(50, 50, 60)
            pdf.cell(140, 6, clean_str(seo.get("title", "N/A")), ln=True)
            
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(108, 92, 231)
            pdf.cell(40, 6, "  Hashtags:", ln=False)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(50, 50, 60)
            # handle lists
            tags = seo.get("hashtags", seo.get("tags", []))
            tags_str = ", ".join(tags) if isinstance(tags, list) else str(tags)
            pdf.cell(140, 6, clean_str(tags_str), ln=True)
            
            # description in metadata box
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(108, 92, 231)
            pdf.cell(40, 6, "  Description Brief:", ln=False)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(50, 50, 60)
            desc = clean_str(seo.get("description", "N/A"))
            pdf.multi_cell(140, 6, desc)
            
            pdf.set_y(current_y + 45 + 10)
        else:
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(0, 6, "No SEO optimisation available.", ln=True)
            pdf.ln(5)
            
        # Section 5 Header: Quality Audit
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(108, 92, 231)
        pdf.cell(0, 10, "5. Automated Quality & Engagement Audit", ln=True)
        pdf.ln(2)
        
        if "quality" in project_data and isinstance(project_data["quality"], dict):
            quality = project_data["quality"]
            overall_score = quality.get("overall_score", 70)
            
            # Visual Score Badge
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(70, 70, 80)
            pdf.cell(60, 10, f"Engagement Score Audit:", ln=False)
            
            # Colored rating label
            if overall_score >= 80:
                pdf.set_fill_color(39, 174, 96) # Green
                pdf.set_text_color(255, 255, 255)
                score_label = f"  {overall_score}/100 - EXCELLENT  "
            elif overall_score >= 60:
                pdf.set_fill_color(241, 196, 15) # Yellow/Orange
                pdf.set_text_color(0, 0, 0)
                score_label = f"  {overall_score}/100 - GOOD  "
            else:
                pdf.set_fill_color(192, 57, 43) # Red
                pdf.set_text_color(255, 255, 255)
                score_label = f"  {overall_score}/100 - NEEDS WORK  "
                
            pdf.set_font("helvetica", "B", 10)
            pdf.cell(60, 8, score_label, border=1, ln=True, fill=True, align="C")
            pdf.ln(4)
            
            # Suggestions
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(70, 70, 80)
            pdf.cell(0, 6, "Optimisation Suggestions:", ln=True)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(50, 50, 60)
            suggestions = quality.get("suggestions", [])
            for item in suggestions[:4]:
                pdf.multi_cell(0, 5, f"- {clean_str(item)}")
        else:
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(0, 6, "No audit data available.", ln=True)
            
        return pdf.output()

    @staticmethod
    def generate_zip_package(project_data: dict) -> bytes:
        """Packages all outputs into a ZIP file."""
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            # Add Script
            if "script" in project_data:
                zip_file.writestr("script.txt", project_data["script"].get("full_script", ""))
                
            # Add Subtitles
            if "subtitles" in project_data:
                zip_file.writestr("captions.srt", project_data["subtitles"].get("srt_content", ""))
                zip_file.writestr("captions.vtt", project_data["subtitles"].get("vtt_content", ""))
                
            # Add PDF Report
            pdf_bytes = ExportService.generate_pdf_report(project_data)
            zip_file.writestr("report.pdf", pdf_bytes)
            
        zip_buffer.seek(0)
        return zip_buffer.getvalue()
